# first_name='Ramu'
# first_name=input("enter your first name:")
# last_name=input('enter your last name:')
# village=input("enter your village:")
# district=input("enter your district:")
# pincode=int(input("enter your pincode"))
# print(f"The user details as follows:\n{first_name} {last_name}\n{village}\n{district}\n{pincode},how are you?")
# print(32+2)
# NUMBERS
# num1=int(input('enter number:'))
# num2=int(input('enter number:'))
# sum=num1+num2
# print(f'The total sum is:{sum}')
# n=int(255)noyno
# print(int(n//10)*10)
# # PREDEFINED MODULES
# import random
# num=random.random()
# print(num)
# n=int(input('enter num'))
# print(n+10)
# print(n+100)
